### ISSUE TITLE
Code is breaking when using image size different from 224x224 (DINOv2)

### ISSUE THREAD

**Issue by tcourat** [mhamilton723/FeatUp#13]
Hi,

I'd like to know if it is expected behavior that the example code in the notebook does not work if we give an input image size which is not 224x224 ? I'd like to use it for other image size, e.g 518x518 (standard image size for DINOv2).

I am especially interested in the upsampler of the DINOv2 model.

I managed to pinpoint a line which implicitly assumes that the input image is of size 224x224 for DINOv2 : https://github.com/mhamilton723/FeatUp/blob/c04e4c19945ce3e98a5488be948c7cc1fdcdacc6/featup/featurizers/DINOv2.py#L439

Indeed, the feature map is reshaped with 16x16 as its spatial dimension, which indicates an original input size of 224x224 as 224=14x16 and DINOv2 uses a patch size of 14. If we provide a different image size, then it will completely change the batch size and everything breaks down in later stages.

It would be nice to make the forward function adaptative to the input image, something such as : 
```
   def forward(self, img, n=1, include_cls=False):
        B,C,H,W = img.shape
        assert H%14 == 0 and W%14==0
        return self.model.forward_features(img)["x_norm_patchtokens"].reshape(-1, H//14, W//14, 384).permute(0, 3, 1, 2)
```

I also noticed that if we keep the default forward function and default image size 224x224, upsampled DINOv2 features are upsampled to 256x256, not 224x224 . This is because DINOv2 uses a patch size of 14, (and hence features map size is divided by 14 wrt the input image size), but the upsampler is upsampling with a factor of 16. We hence need to downsize them back with a scale factor of 14/16 :

```
upsampler = torch.hub.load("mhamilton723/FeatUp", 'dinov2').cuda() # image tensor has size 224x224
hr_feats = upsampler(image_tensor) # feature map has size 256x256
hr_feats_14 = torch.nn.functional.interpolate(hr_feats, scale_factor=14/16, mode="bilinear") # feature map has size 224x224
```

**Comment by Becktor** [comment]
This should be reshaped to (-1,14,14,384)

**Comment by liutongkun** [comment]
> Hi,
> 
> I'd like to know if it is expected behavior that the example code in the notebook does not work if we give an input image size which is not 224x224 ? I'd like to use it for other image size, e.g 518x518 (standard image size for DINOv2).
> 
> I am especially interested in the upsampler of the DINOv2 model.
> 
> I managed to pinpoint a line which implicitly assumes that the input image is of size 224x224 for DINOv2 :
> 
> https://github.com/mhamilton723/FeatUp/blob/c04e4c19945ce3e98a5488be948c7cc1fdcdacc6/featup/featurizers/DINOv2.py#L439
> 
> Indeed, the feature map is reshaped with 16x16 as its spatial dimension, which indicates an original input size of 224x224 as 224=14x16 and DINOv2 uses a patch size of 14. If we provide a different image size, then it will completely change the batch size and everything breaks down in later stages.
> 
> It would be nice to make the forward function adaptative to the input image, something such as :
> 
> ```
>    def forward(self, img, n=1, include_cls=False):
>         B,C,H,W = img.shape
>         assert H%14 == 0 and W%14==0
>         return self.model.forward_features(img)["x_norm_patchtokens"].reshape(-1, H//14, W//14, 384).permute(0, 3, 1, 2)
> ```

I have the same problem, sir, have you solved it?

**Comment by tcourat** [comment]
> > Hi,
> > I'd like to know if it is expected behavior that the example code in the notebook does not work if we give an input image size which is not 224x224 ? I'd like to use it for other image size, e.g 518x518 (standard image size for DINOv2).
> > I am especially interested in the upsampler of the DINOv2 model.
> > I managed to pinpoint a line which implicitly assumes that the input image is of size 224x224 for DINOv2 :
> > https://github.com/mhamilton723/FeatUp/blob/c04e4c19945ce3e98a5488be948c7cc1fdcdacc6/featup/featurizers/DINOv2.py#L439
> > 
> > Indeed, the feature map is reshaped with 16x16 as its spatial dimension, which indicates an original input size of 224x224 as 224=14x16 and DINOv2 uses a patch size of 14. If we provide a different image size, then it will completely change the batch size and everything breaks down in later stages.
> > It would be nice to make the forward function adaptative to the input image, something such as :
> > ```
> >    def forward(self, img, n=1, include_cls=False):
> >         B,C,H,W = img.shape
> >         assert H%14 == 0 and W%14==0
> >         return self.model.forward_features(img)["x_norm_patchtokens"].reshape(-1, H//14, W//14, 384).permute(0, 3, 1, 2)
> > ```
> 
> I have the same problem, sir, have you solved it?

Hi. You can modify the forward function of the DINOv2 featurizer with the one I written. 
I did not try with other featurizers.

**Comment by liutongkun** [comment]
> > I have the same problem, sir, have you solved it?
> 
> Hi. You can modify the forward function of the DINOv2 featurizer with the one I written (or just replace the 16,16 dimensions in the reshape by the height and width of your input image divided by 14).
> 
> I did not try with other featurizers.
> 
> It seems to work at least visually. Only issue is that the upsampler can only upsamples to x2, x4, x8 and x16 (x16 by default) resolutions but not explicitly x14. Hence you may need to downsample a bit the upsampled features back to 518x518 because you'll get 592x592 upsampled features maps if you use DINOv2 upsampler.
> 
> However I am unsure if this affects the upsampler output quality, I do not know if some components of the upsamplers were explicitly trained with a 224x224 input size in an absolute manner. Maybe the authors can clarify this point.

Thank you very much for your detailed reply!

**Comment by mhamilton723** [comment]
THank you for finding this! I have commited a fixed version similiar to that proposed by @liutongkun  :)
