### ISSUE TITLE
Different Upsimpling

### ISSUE THREAD

**Issue by BasDiaz** [mhamilton723/FeatUp#17]
Amazing work! I would like to learn more.
In figure 5 you show different upsampling methods, Are they tuned with the FeatUp pipeline, e.g. the JBU filters were replaced by bilinear interpolation while still using the same training pipeline and loss? or that figure just shows the results of plain bilinear interpolation applied to the frozen feature volumes?

If it's the later, did you try another upsampling block but using the same training pipeline and loss?

Thanks!

![image](https://github.com/mhamilton723/FeatUp/assets/93609007/ab022639-16c8-418b-9cf4-a68f9f110b79)

**Comment by mhamilton723** [comment]
Hey @BasDiaz any of the upsamplers in this figure that have tunable parameters were fit using the same loss as the JBU. (Our multi-view loiss)
