### ISSUE TITLE
JBU FILTER / torch.Unfold

### ISSUE THREAD

**Issue by BasDiaz** [mhamilton723/FeatUp#21]
I'd like to run the FeatUp training in accelerators that are not CUDA based.
Are there any suggestion to run the JBU filters with torch.Unfold?

**Comment by mhamilton723** [comment]
Theres also a CPU implementation of the op, but if you would like a (much less efficient) implementation with unfold you can check out this pure pytorch implementation of the AdaptiveConv operator

https://github.com/mhamilton723/FeatUp/issues/4#issuecomment-2007591205

**Comment by BasDiaz** [comment]
Thank you for the suggestion. Unfortunately, that native torch implementation is too inefficient and the training runs out of memory right away, not even with 64GB GPU.
Do you know if is there a better way (besides the CUDA implementation)?
