### ISSUE TITLE
Question about feature compression with PCA

### ISSUE THREAD

**Issue by sangminkim-99** [mhamilton723/FeatUp#24]
Hi @mhamilton723, 
Thank you for sharing this great work!

I have a query regarding the feature compression aspect outlined in your paper. 
Specifically, in Section 3.3, you mentioned compressing the feature with the top 128 dimensions of PCA, which explain approximately 96% of the variance across a single image's features.

Could you kindly elaborate on how you arrived at the figure of 96%?

Thank you.

**Comment by mhamilton723** [comment]
Hey, i dont remember exactly what my experimental setup was to recreate this number but the basic gist was to use this connection between PCA eigenvalues and explained variance:

https://saturncloud.io/blog/what-is-sklearn-pca-explained-variance-and-explained-variance-ratio-difference/#:~:text=and%20so%20on.-,Explained%20Variance%20in%20Sklearn%20PCA,eigenvalue%20associated%20with%20that%20component.

I likely did this over a few sample images when trying this out just to make sure nothing too bad was slipping through the cracks

**Comment by sangminkim-99** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2024-03-29T03:03:10
          
          
            * 메일 제목 : 
Re: [mhamilton723/FeatUp] Question about feature compression with PCA (Issue #24)
          
          
            
              
                * 실패 사유 : 
              
              
                
대외비/기밀 메일은 외부 계정으로 발송이 제한되어 일부 메일 발송 실패(수신자가 전달 설정한 경우 포함)
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.
