### ISSUE TITLE
smoothing out blurriness in features ?

### ISSUE THREAD

**Issue by odusseys** [mhamilton723/FeatUp#30]
I'm using the dinov2 backbone ; Ive noticed that overall while the results are very detailed (great job!) there is some haziness / bleeding of the values around areas where the semantics change. For example there will be a halo around an object, etc. I am guessing this is due to the limitations of upscaling the feature maps, which can't be perfect during training.
Do you have any recommendations on how to avoid these artefacts ?

**Comment by odusseys** [comment]
adding some images to explain exactly what I mean

![image](https://github.com/mhamilton723/FeatUp/assets/7863870/1852ecdc-7d45-40db-9a07-658435991a09)

![image](https://github.com/mhamilton723/FeatUp/assets/7863870/257a2670-00dc-42f1-a1d6-5b0f7dd452ea)

**Comment by vcadillog** [comment]
It doesn't seem to be workaround to solve this with the default upscalers, but you can fit the implicit model to your image and obtain features with better quality and sharpness.

**Comment by mhamilton723** [comment]
hey @odusseys yes the JBU operators can only clean up so much. As mentioned by @vcadillog the implicit upsampler is overfit to a single image and tends to be alot sharper.
