### ISSUE TITLE
Question about training with FeatUp as the upsampling op for a downstream task

### ISSUE THREAD

**Issue by praeclarumjj3** [mhamilton723/FeatUp#7]
Hi, first of all, thanks for the excellent work. It is one of the most remarkable papers I have read in a while!

I noticed that in the paper, you have an experiment comparing `Bilinear` to `FeatUp` in Tab. 1 during inference. I have two questions:

- Is the `Bilinear` op performed through `torch.nn.functional.interpolate()` or something else?
- Did you try using FeatUp as the upsampling operation during training, let's say, a segmentation model to compare the performance gap? I would expect the performance to be even better.

**Comment by mhamilton723** [comment]
Thanks for the kind words :)

1. Yes its just interpolate 
2. Yes! See table 2 in the paper

![image](https://github.com/mhamilton723/FeatUp/assets/6456637/6d7748c1-22ac-4034-aeaf-948db42c7523)

**Comment by praeclarumjj3** [comment]
Ahh I see, missed Tab. 2, thanks!
